version: '3'
services:
  db:
    restart: always
    image: cgr.dev/chainguard/postgres:latest
    stop_grace_period: 1m
    networks:
      - internal_network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
    volumes:
      - /mastodon/postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:7.0-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - /mastodon/redis:/data

  es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
    volumes:
      - /mastodon/elasticsearch:/usr/share/elasticsearch/data

  web:
    image: yakumosaki/glitch-soc
    restart: always
    env_file: env.production
    command: bash -c "rm -f /opt/mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --proxy=off localhost:3000/api/v1/instance || exit 1"]
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
#      - es
    volumes:
      - /mastodon/public/system:/opt/mastodon/public/system

  streaming:
    image: yakumosaki/glitch-soc
    restart: always
    env_file: env.production
    command: yarn start
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --proxy=off localhost:4000/api/v1/streaming/health || exit
1"]
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    image: yakumosaki/glitch-soc
    restart: always
    env_file: env.production
    environment:
      DB_POOL: 20
    command: bundle exec sidekiq -c 20
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - /mastodon/public/system:/mastodon/public/system

networks:
  external_network:
    internal: false
  internal_network:
    internal: true

