name: Build glitch-soc docker Image

on:
  repository_dispatch:
    types:
      - webhook
env:
  mastodon_url: "https://github.com/glitch-soc/mastodon.git"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'glitch-soc更新があるかチェック'
      run: |
        WORK=`pwd`
        
        # local docker image tag
        DOCKER_TAG=`date '+%Y%m%d_%H'`
        DOCKERHUB_IMAGENAME="yakumosaki/glitch-soc"

        git clone ${{ env.mastodon_url }}
        
        ${WORK}/build.sh $DOCKERHUB_IMAGENAME $DOCKER_TAG
