name: Build glitch-soc docker Image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      force:
        description: 'Force create '
        type: boolean
        default: false 
      dryrun:
        description: 'Dry-run'
        type: boolean
        default: false 
env:
  mastodon_url: "https://github.com/glitch-soc/mastodon.git"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'glitch-soc更新があるかチェック'
      run: |
        WORK=`pwd`
        
        # local docker image tag
        DOCKER_TAG=`date '+%Y%m%d_%H'`
        DOCKERHUB_IMAGENAME="yakumosaki/glitch-soc"

        #git clone ${{ env.mastodon_url }}
        #
        #${WORK}/build.sh $DOCKERHUB_IMAGENAME $DOCKER_TAG
