name: Build glitch-soc docker Image

on:
  repository_dispatch:
    types:
      - webhook
env:
  mastodon_url: "https://github.com/glitch-soc/mastodon.git"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'Build glitch-soc docker image'
      run: |
        WORK=`pwd`
        
        # local docker image tag
        DOCKER_TAG=`date '+%Y%m%d_%H'`
        DOCKERHUB_IMAGENAME="yakumosaki/glitch-soc"

        git clone ${{ env.mastodon_url }}
        
        ${WORK}/build.sh $DOCKERHUB_IMAGENAME $DOCKER_TAG
        
        echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
        
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push latest
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: user/app:latest

    - name: Build and push tag
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: user/app:${{ env.DOCKER_TAG }}
